#!/usr/bin/env bash

# hrsync by Daniele Paroli
# Additions by Christian Garbs and paskalito
#
# simple script to backup a directory with rsync detecting moved and renamed files
#
# use it at your own risk, please see README and LICENSE files

# ------------------------------------------------------------
# Backup source and target directory 

Source="${1%/}"
Target="${2%/}"
TargetHost=$3

# ------------------------------------------------------------


# if remote host is set, set SSHPort to user specified value else set it to 22
if [ -n "$3" ]
then
	if [ -z "$4" ]
	then
		SSHPort=22
	else
		SSHPort=$4
	fi
	echo "SSH Port is: $SSHPort"
fi


# Name of shadow directory
Shadow=".rsync_shadow"


# Start doing things

if [ "${Source:0:1}" != / ]
then
	echo "Source path needs to be an absolute path"
	exit 0
fi

if [ "${Target:0:1}" != / ]
then
	echo "Target path needs to be an absolute path"
	exit 0
fi

if [ -z "$2" ]
then
	echo "Usage:"
	echo "	hrsync source target"
	echo "	hrsync source target remoteHost"
	echo "Example:"
	echo "	hrsync /home/user/Documents /mnt/external/Documents"
	echo "	hrsync /home/user/Documents /root/Documents root@example.com"
	echo "Please see the README file"

	exit 0
fi


if [ ! -d "$Source/$Shadow" ] 
then
	# first time run: create source shadow
	rsync -a --delete --link-dest="$Source" --exclude="/$Shadow" "$Source"/ "$Source/$Shadow"
fi

# do real syncronization
if [ -z "$3" ]
then
	# local version
	rsync -axXhHv --stats --no-inc-recursive --numeric-ids --delete --delete-after "$Source"/ "$Target"
else
	# remote version
	rsync -axXhHv --stats --no-inc-recursive --numeric-ids --delete --delete-after "$Source"/ -e "ssh -p $SSHPort" $TargetHost:"'$Target'"
fi

status=$?

if [ $status -eq 0 ]
then
	#update source shadow directory
	rsync -a --delete --link-dest="$Source" --exclude="/$Shadow" "$Source"/ "$Source/$Shadow"

	#update target shadow directory
	if [ -z "$3" ]
	then
		# local version
		rsync -a --delete --link-dest="$Target" --exclude="/$Shadow" "$Target/" "$Target/$Shadow"
	else
		# remote version
		ssh -p $SSHPort $TargetHost "rsync -a --delete --link-dest='$Target' --exclude='/$Shadow' '$Target/' '$Target/$Shadow'"
	fi
fi

exit $status
